### ISSUE TITLE
Bar chart doesn't update when data updated.

### ISSUE THREAD

**Issue by bcyng** [marekpridal/BarChart#10]
**Describe the bug**
Bar chart doesn't update when data updated on swiftui version

**To Reproduce**
1. change data after chart is displayed
2. chart doesn't get updated.

**Comment by marekpridal** [comment]
Can you send code snippet which you use for updating the data and also iOS version and Xcode version you are using?

**Comment by marekpridal** [comment]
Closing because of missing reaction from issue creator.
