### ISSUE TITLE
Update Barchart 

### ISSUE THREAD

**Issue by TrsUix** [marekpridal/BarChart#13]
Hello I want to update the Barchart on the fly

var elementList = BarChartView.DataSet.DataElement(date: nil, xLabel: "Feb", bars: [BarChartView.DataSet.DataElement.Bar(value: 10, color: UIColor.green)])

VStack{
BarChart(dataSet: BarChart.DataSet(elements: self.elementList, selectionColor: Color.blue), selectedElement: $selectedElement,
                                 barWidth: 15.0).font(Font.custom("ProximaSoft-Bold", size: 20))
}

// update elementList after REST Call
restCall(){
    self.elementList = BarChartView.DataSet.DataElement(date: nil, xLabel: "Marc", bars: [BarChartView.DataSet.DataElement.Bar(value: 100, color: UIColor.green)])

// update BarChart ???
}

// How can I update the BarChart???

**Comment by marekpridal** [comment]
Annotating your ```var elementList``` with ```@State``` property wrapper should do the trick.
